name: Generate Snake

on:
  # Runs every 6 hours to keep the contribution graph updated
  schedule:
    - cron: "0 */6 * * *"
  # Allows us to manually run the workflow from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Generate the snake contribution graph
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: 7AkhilV 
          outputs: |
            dist/github-contribution-grid-snake.svg

      # Upload the snake animation to GitHub Pages
      - name: Push to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
